[app]
GOOGLE_API_KEY = "AlzaSyDIW_dm161XVmzqlGBC5FzIOfjSeSfecwc"
MONGODB_URI = "mongodb+srv://Andres:3e4r5t6y@agalvan.s86cjsl.mongodb.net/"
USER = "Andres Galvan"
COHERE_API_KEY = "LBcesYb1DZ4GYGskMRehzFRYBu2i7uaF2LIfxPO4"

[b2]
B2_BUCKET_NAME = "BackBlaze"
B2_READ_KEY_ID = "005af907baae6ce0000000003"
B2_READ_APPLICATION_KEY = "K005Oem4eP+T5sQU6f+/Ikn3VJeMk24"
B2_WRITE_KEY_ID = "005af907baae6ce0000000004"
B2_WRITE_APPLICATION_KEY = "K005g1zTM1Vdc9GyYuDNGteI/KWgzA"
